const CURRICULUM = [
  {
    id: "bases-datos",
    short: "BD",
    name: "Bases de datos",
    url: "https://campusfp.unir.net/courses/3427",
    topicLabel: "Tema",
    testsTotal: 10,
    activitiesTotal: 3,
    topics: [
      {
        number: 1,
        title: "Sistemas de almacenamiento de la información",
        weeks: [3, 4],
      },
      {
        number: 2,
        title: "Diseño conceptual de base de datos",
        weeks: [5, 7],
      },
      {
        number: 3,
        title: "Modelo lógico relacional",
        weeks: [8, 10],
      },
      {
        number: 4,
        title: "SQL: comenzamos con consultas",
        weeks: [12, 13],
      },
      {
        number: 5,
        title: "Consultas avanzadas",
        weeks: [14, 15],
      },
      {
        number: 6,
        title: "Diseño físico de la BD",
        weeks: [16, 17],
      },
      {
        number: 7,
        title: "Vistas, índices, optimización y administración",
        weeks: [18, 20],
      },
      {
        number: 8,
        title: "Programación en SQL",
        weeks: [22, 23],
      },
      {
        number: 9,
        title: "Gestión de la seguridad en BD",
        weeks: [24, 26],
      },
      {
        number: 10,
        title: "Otros SGBD",
        weeks: [27, 28],
      },
    ],
  },
  {
    id: "entornos-desarrollo",
    short: "ED",
    name: "Entornos de desarrollo",
    url: "https://campusfp.unir.net/courses/3430",
    topicLabel: "Tema",
    testsTotal: 10,
    activitiesTotal: 2,
    topics: [
      { number: 1, title: "Concepto de programa", weeks: [3, 4] },
      { number: 2, title: "Ingeniería de software", weeks: [5, 7] },
      { number: 3, title: "Entornos de desarrollo: instalación y configuración", weeks: [8, 9] },
      { number: 4, title: "Control de versiones", weeks: [12, 14] },
      { number: 5, title: "Depuración de código y generación de documentación", weeks: [15, 16] },
      { number: 6, title: "Elaboración de pruebas", weeks: [17, 18] },
      { number: 7, title: "Desarrollo de software en proyectos", weeks: [19, 19] },
      { number: 8, title: "Herramientas para análisis del programa", weeks: [22, 23] },
      { number: 9, title: "Herramientas UML", weeks: [24, 26] },
      { number: 10, title: "Herramientas CASE", weeks: [27, 28] },
    ],
  },
  {
    id: "ingles",
    short: "IN",
    name: "Inglés",
    url: "https://campusfp.unir.net/courses/3429",
    topicLabel: "Unidad",
    testsTotal: 5,
    activitiesTotal: 0,
    topics: [
      { number: 1, title: "Professional Self-presentation", weeks: [3, 6] },
      { number: 2, title: "Business Communication", weeks: [7, 10] },
      { number: 3, title: "Public Speaking and Meetings", weeks: [12, 16] },
      { number: 4, title: "Handling Workplace Interactions", weeks: [17, 20] },
      { number: 5, title: "Job Search", weeks: [22, 28] },
    ],
  },
  {
    id: "empleabilidad",
    short: "IE",
    name: "Itinerario para la empleabilidad",
    url: "https://campusfp.unir.net/courses/3425",
    topicLabel: "Tema",
    testsTotal: 10,
    activitiesTotal: 2,
    topics: [
      { number: 1, title: "Seguridad y salud en el trabajo", weeks: [3, 5] },
      { number: 2, title: "La prevención en la empresa", weeks: [6, 8] },
      { number: 3, title: "Prevención y actuación en caso de emergencia", weeks: [9, 10] },
      { number: 4, title: "La relación laboral", weeks: [12, 13] },
      { number: 5, title: "El contrato de trabajo y la jornada laboral", weeks: [14, 16] },
      { number: 6, title: "El recibo del salario y la Seguridad Social", weeks: [17, 20] },
      { number: 7, title: "Libertad sindical y representación en la empresa", weeks: [22, 22] },
      { number: 8, title: "Análisis del sector profesional", weeks: [23, 24] },
      { number: 9, title: "El proyecto profesional", weeks: [25, 26] },
      { number: 10, title: "El aprendizaje autónomo", weeks: [27, 28] },
    ],
  },
  {
    id: "lenguajes-marcas",
    short: "LM",
    name: "Lenguajes de marcas y sistemas de gestión de información",
    url: "https://campusfp.unir.net/courses/3431",
    topicLabel: "Tema",
    testsTotal: 10,
    activitiesTotal: 2,
    topics: [
      { number: 1, title: "Introducción a los lenguajes de marcas", weeks: [3, 4] },
      { number: 2, title: "Ficheros XML y JSON", weeks: [5, 6] },
      { number: 3, title: "Validación y transformación de documentos", weeks: [7, 8] },
      { number: 4, title: "Transformación", weeks: [12, 13] },
      { number: 5, title: "Uso de lenguajes de marcas en entornos web: HTML", weeks: [14, 15] },
      { number: 6, title: "HTML: componentes avanzados", weeks: [16, 17] },
      { number: 7, title: "Hojas de estilo: CSS", weeks: [18, 19] },
      { number: 8, title: "JavaScript", weeks: [22, 23] },
      { number: 9, title: "XML para almacenamiento", weeks: [24, 26] },
      { number: 10, title: "Sistemas de gestión empresarial", weeks: [27, 28] },
    ],
  },
  {
    id: "programacion",
    short: "PR",
    name: "Programación",
    url: "https://campusfp.unir.net/courses/3426",
    topicLabel: "Tema",
    testsTotal: 10,
    activitiesTotal: 3,
    topics: [
      { number: 1, title: "Introducción a la programación", weeks: [3, 3] },
      { number: 2, title: "Elementos básicos del lenguaje", weeks: [4, 5] },
      { number: 3, title: "Estructuras de control", weeks: [6, 7] },
      { number: 4, title: "Funciones", weeks: [8, 10] },
      { number: 5, title: "Programación orientada a objetos", weeks: [12, 14] },
      { number: 6, title: "Herencia e interfaces", weeks: [15, 16] },
      { number: 7, title: "Colecciones y manejo de excepciones", weeks: [17, 18] },
      { number: 8, title: "Entrada/salida de información", weeks: [26, 28] },
      { number: 9, title: "Bases de datos orientadas a objetos", weeks: [22, 25] },
      { number: 10, title: "Acceso a bases de datos con Java", weeks: [19, 20] },
    ],
  },
  {
    id: "sistemas-informaticos",
    short: "SI",
    name: "Sistemas informáticos",
    url: "https://campusfp.unir.net/courses/3428",
    topicLabel: "Tema",
    testsTotal: 10,
    activitiesTotal: 3,
    topics: [
      { number: 1, title: "Introducción a los sistemas informáticos", weeks: [3, 4] },
      { number: 2, title: "Sistemas operativos", weeks: [5, 7] },
      { number: 3, title: "Instalación de sistemas operativos", weeks: [8, 10] },
      { number: 4, title: "Windows", weeks: [12, 13] },
      { number: 5, title: "Programación batch (Windows)", weeks: [14, 15] },
      { number: 6, title: "Linux", weeks: [16, 17] },
      { number: 7, title: "Programación Bash (Linux)", weeks: [18, 20] },
      { number: 8, title: "Sistemas en red", weeks: [22, 23] },
      { number: 9, title: "Diseño de redes", weeks: [24, 26] },
      { number: 10, title: "Seguridad informática", weeks: [27, 28] },
    ],
  },
];
